// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2XfyqLaCkP36wwmdDnDn2PaD7ofPVmw',
    appId: '1:863240345118:web:429ed9e55ebb715138000f',
    messagingSenderId: '863240345118',
    projectId: 'growlit-f0da9',
    authDomain: 'growlit-f0da9.firebaseapp.com',
    storageBucket: 'growlit-f0da9.firebasestorage.app',
    measurementId: 'G-P7Q54ECZ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu04mOyOqbn4SUuBq-d2Dfda6rBHq_XMA',
    appId: '1:863240345118:android:45b6f4978d8fccaf38000f',
    messagingSenderId: '863240345118',
    projectId: 'growlit-f0da9',
    storageBucket: 'growlit-f0da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhz14vSYT5z_x27EpC6xPNDJu0824S010',
    appId: '1:863240345118:ios:67468c1addd2106938000f',
    messagingSenderId: '863240345118',
    projectId: 'growlit-f0da9',
    storageBucket: 'growlit-f0da9.firebasestorage.app',
    iosBundleId: 'com.example.growlitMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhz14vSYT5z_x27EpC6xPNDJu0824S010',
    appId: '1:863240345118:ios:67468c1addd2106938000f',
    messagingSenderId: '863240345118',
    projectId: 'growlit-f0da9',
    storageBucket: 'growlit-f0da9.firebasestorage.app',
    iosBundleId: 'com.example.growlitMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc2XfyqLaCkP36wwmdDnDn2PaD7ofPVmw',
    appId: '1:863240345118:web:959bf8fbb9a20bd238000f',
    messagingSenderId: '863240345118',
    projectId: 'growlit-f0da9',
    authDomain: 'growlit-f0da9.firebaseapp.com',
    storageBucket: 'growlit-f0da9.firebasestorage.app',
    measurementId: 'G-TMTLLPK767',
  );
}
